apiVersion : apps/v1
kind: Deployment
metadata:
  name: tracker
  labels:
    app: tracker 
spec:
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 8
  selector:
    matchLabels:
      app: tracker
  template:
    metadata:
      labels:
        app: tracker 
    spec:
      containers:
        - name: test
          image: acralexsela.azurecr.io/traker:latest



