apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
    kubernetes.azure.com/generator: devhub
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: akstestsela.azurecr.io/image-workflow-1718894485555:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
